### ISSUE TITLE
Header missing END card

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/HERA-Beams#10]
All the files error on pyuvbeam.UVBeam.read_beamfits with `IOError: Missing END card`.
See full error [here](https://github.com/dannyjacobs/beam_errors/blob/trunk/Delay_Beam.ipynb)

**Comment by bhazelton** [comment]
Did you install `gitlfs` per the readme? If not you don't have the real files. A quick way to check is to look at their sizes, they should be hundreds of MB not a few kB.

**Comment by dannyjacobs** [comment]
This was the problem. I added an "Installation" section header on the readme to highlight this step.
